apiVersion: apps/v1
kind: Deployment
metadata:
  name: REPO_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: prod
  template:
    metadata:
      labels:
        environment: prod
    spec:
      imagePullSecrets:
      - name: cool-api-prod
      containers:
      - name: REPO_NAME
        env:
        - name: ENVIRONMENT
          value: "production"
