namespace: kube-apps-qa

bases:
  - ../../base

commonLabels:
  app: cool-example-api
  env: qa

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

resources:
  - ingress.yaml

namePrefix: qa-
